mirmir_proj/mirmir_app/urls.py
from django.urls import path
from . import views
from django.conf import settings

app_name = 'mirmir_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('main/', views.main, name='main'),
    path('about/', views.about, name='about'),
    path('mead_club/', views.club, name='club'),
    path('archive/', views.archive, name='archive'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('employee_main/', views.employee_main, name='employee_main'),
    path('main_page_management/', views.main_page_management,
         name='main_page_management'),
    path('highlights/', views.highlights, name='highlights'),
    path('get_warning/', views.get_warning, name='get_warning'),
    path('get_carousele/', views.get_carousele, name='get_carousele'),
    path('save_slide/', views.save_slide, name='save_slide'),
    path('save_highlight/', views.save_highlight, name='save_highlight'),
    path('save_warning/', views.save_warning, name='save_warning'),
    path('add_new_slide/', views.add_new_slide, name='add_new_slide'),
    path('execute_delete/', views.execute_delete, name='execute_delete'),
    path('save_new_highlight/', views.save_new_highlight,
         name='save_new_highlight'),
    path('profile/', views.profile, name='profile'),
    path('shop/', views.shop, name='shop'),
    path('shop_get_product_data/', views.shop_get_product_data,
         name='shop_get_product_data'),
    path('checkout/', views.checkout, name='checkout'),
    path('get_user_data_for_checkout/', views.get_user_data_for_checkout,
         name='get_user_data_for_checkout'),
    path('cart_verification/', views.cart_verification, name='cart_verification'),
    path('upsert_order/', views.upsert_order, name='upsert_order'),
    path('order_details/<int:order_num>/',
         views.order_details, name="order_details"),
    path('get_open_orders/', views.get_open_orders, name='get_open_orders'),
    path('save_order_changes/', views.save_order_changes,
         name='save_order_changes'),
    path('get_next_order_number_employee/', views.get_next_order_number_employee,
         name='get_next_order_number_employee'),
    path('get_active_products/', views.get_active_products,
         name='get_active_products'),
    path('save_product_changes/', views.save_product_changes,
         name='save_product_changes'),
    path('save_photo/', views.save_photo, name='save_photo'),
    path('send_new_code/', views.send_new_code, name='send_new_code'),
    path('confirm/', views.confirm, name='confirm'),
    path('email_sent/', views.email_sent, name='email_sent'),
    path('send_email/', views.send_email, name='send_email'),
    path('send_customer_email/', views.send_customer_email,
         name='send_customer_email'),
    path('confirm_login/', views.confirm_login, name='confirm_login'),
    path('reset_password_request/', views.reset_password_request,
         name='reset_password_request'),
    path('change_password/', views.change_password, name='change_password'),
    path('logged_in_password_reset/', views.logged_in_password_reset,
         name='logged_in_password_reset'),
]

mirmir_proj/mirmir_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mirmir_app.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler500 = 'mirmir_app.views.handler500'

mirmir_proj/mirmir_app/forms.py
from django.forms import ModelForm, TextInput, DateField, DateInput
from django import forms
from .models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        # fields = '__all__'
        exclude = ['username', 'status', 'email_address_confirmed']
        widgets = {
            'birthday': TextInput(attrs={'type': 'date'})
        }


# date_field = forms.DateField(
#     widget=forms.TextInput(
#         attrs={'type': 'date'}
#     )
# )

mirmir_proj/mirmir_app/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib import auth
from django.core import serializers
from django.core.mail import send_mail
from django.template.loader import render_to_string
from .models import StatusField, SortField, Contact, Product, CarouselSlide, MainPageWarning, MainPageHighlight, Order, OrderType, PaymentStatus, OrderItemQuantity, ShippingStatus, ProductPhoto, TransactionType, EmailConfirmation
import requests
import random
import django.contrib.auth
from django.views.generic import CreateView
from .forms import ContactForm
from . import utilities
import json
import re
import string
from datetime import datetime

####################################
#         Employee Views           #
####################################


def employee_check(user):
    return user.profile.status.status == 'employee'


@user_passes_test(employee_check)
def send_email(request):
    data = json.loads(request.body)
    print(data)
    status_id = data['email_select_by_status']
    contacts = Contact.objects.filter(status=status_id)
    email_addresses = []
    for contact in contacts:
        email_addresses.append(contact.email)
    email_text = data['email_text']
    body = render_to_string(
        'mirmir_app/employee_email.html', {'email_text': email_text})
    send_mail('News From Mirmir', '', settings.EMAIL_HOST_USER,
              email_addresses, fail_silently=False, html_message=body)
    return JsonResponse({'blank_text': ''})


@user_passes_test(employee_check)
def send_customer_email(request):
    data = json.loads(request.body)
    print(data)
    email_address = data['email_address']
    email_text = data['email_text']
    body = render_to_string(
        'mirmir_app/employee_email.html', {'email_text': email_text})
    send_mail('News About Your Order', '', settings.EMAIL_HOST_USER,
              [email_address], fail_silently=False, html_message=body)
    return JsonResponse({'blank_text': ''})


@user_passes_test(employee_check)
def save_photo(request):
    data = request.POST
    print(data)
    product = Product.objects.get(id=request.POST['product_id'])
    new_num = product.product_photos.count() + 1
    new_photo = ProductPhoto(
        photo=request.FILES['image'], photo_image_number=new_num, product=product)
    new_photo.save()
    return HttpResponse('image saved')


@user_passes_test(employee_check)
def save_product_changes(request):
    product_update = json.loads(request.body)['product']
    type_of_update = json.loads(request.body)['type']
    photo_remove_instructions = json.loads(
        request.body)['photo_remove_instructions']
    if type_of_update == 'update':
        # print(product_update)
        product = Product.objects.get(id=product_update['id'])
        print(product)
        product.title = product_update['title']
        product.subtitle = product_update['subtitle']
        product.action_message = product_update['action_message']
        product.is_active = product_update['is_active']
        product.is_display_on_website = product_update['is_display_on_website']
        product.description = product_update['description']
        product.description_teaser = product_update['description_teaser']
        product.SKU_unit_description = product_update['SKU_unit_description']
        product.SKU_min_order_qty = product_update['SKU_min_order_qty']
        product.SKU_max_order_qty = product_update['SKU_max_order_qty']
        product.SKU_order_in_multiples_of = product_update['SKU_order_in_multiples_of']
        product.SKU_is_non_taxable = product_update['SKU_is_non_taxable']
        product.SKU_is_no_shipping_charge = product_update['SKU_is_no_shipping_charge']
        product.SKU_Prices_price_level = product_update['SKU_Prices_price_level']
        product.SKU_Prices_price = product_update['SKU_Prices_price']
        product.SKU_Prices_price_quantity = product_update['SKU_Prices_price_quantity']
        product.SKU_Prices_is_inventory_on = product_update['SKU_Prices_is_inventory_on']
        product.SKU_Prices_Inventory_current_inventory = product_update[
            'SKU_Prices_Inventory_current_inventory']
        product.SKU_Prices_Inventory_inventory_pool = product_update[
            'SKU_Prices_Inventory_inventory_pool']
        product.WineProperties_tasting_notes = product_update['WineProperties_tasting_notes']
        product.WineProperties_wine_maker_notes = product_update['WineProperties_wine_maker_notes']
        product.WineProperties_food_pairing_notes = product_update[
            'WineProperties_food_pairing_notes']
        for photo_id in photo_remove_instructions:
            tmp_photo = ProductPhoto.objects.get(id=photo_id)
            tmp_photo.delete()
        product.save()
        return HttpResponse(product_update['id'])

    elif type_of_update == 'new':
        print(product_update)
        # bottling_date = re.split('/', product_update['bottling_date'])
        # final_bottling_date = bottling_date[2] + '-' + \
        #     bottling_date[0] + '-' + bottling_date[1]
        new_product = Product(
            product_type=product_update['product_type'],
            title=product_update['title'],
            POSTitle=product_update['POSTitle'],
            brand=product_update['brand'],
            subtitle=product_update['subtitle'],
            action_message=product_update['action_message'],
            is_active=product_update['is_active'],
            is_display_on_website=product_update['is_display_on_website'],
            description=product_update['description'],
            description_teaser=product_update['description_teaser'],
            SKU_SKU=product_update['SKU_SKU'],
            SKU_cost_of_good=product_update['SKU_cost_of_good'],
            SKU_UPC_code=product_update['SKU_UPC_code'],
            SKU_unit_description=product_update['SKU_unit_description'],
            SKU_min_order_qty=product_update['SKU_min_order_qty'],
            SKU_max_order_qty=product_update['SKU_max_order_qty'],
            SKU_order_in_multiples_of=product_update['SKU_order_in_multiples_of'],
            SKU_weight=product_update['SKU_weight'],
            SKU_is_non_taxable=product_update['SKU_is_non_taxable'],
            SKU_is_no_shipping_charge=product_update['SKU_is_no_shipping_charge'],
            SKU_Prices_price_level=product_update['SKU_Prices_price_level'],
            SKU_Prices_price=product_update['SKU_Prices_price'],
            SKU_Prices_price_quantity=product_update['SKU_Prices_price_quantity'],
            SKU_Prices_is_inventory_on=product_update['SKU_Prices_is_inventory_on'],
            SKU_Prices_Inventory_current_inventory=product_update[
                'SKU_Prices_Inventory_current_inventory'],
            SKU_Prices_Inventory_inventory_pool=product_update['SKU_Prices_Inventory_inventory_pool'],
            WineProperties_bottles_in_case=product_update['WineProperties_bottles_in_case'],
            WineProperties_bottle_size_in_ml=product_update['WineProperties_bottle_size_in_ml'],
            WineProperties_type=product_update['WineProperties_type'],
            WineProperties_alcohol=product_update['WineProperties_alcohol'],
            WineProperties_bottling_date=product_update['WineProperties_bottling_date'],
            WineProperties_tasting_notes=product_update['WineProperties_tasting_notes'],
            WineProperties_wine_maker_notes=product_update['WineProperties_wine_maker_notes'],
            WineProperties_food_pairing_notes=product_update['WineProperties_food_pairing_notes']
        )
        new_product.save()
        return HttpResponse(new_product.id)
    else:
        return HttpResponse('error')

    product.save()
    return HttpResponse('Ok')


@user_passes_test(employee_check)
def get_active_products(request):
    data = Product.get_active_products()
    return JsonResponse({'data': data})


@user_passes_test(employee_check)
def get_next_order_number_employee(request):
    return HttpResponse(Order.objects.count() + 1)


@user_passes_test(employee_check)
def save_order_changes(request):
    # print(request.body)
    order_update = json.loads(request.body)['order']
    type_of_update = json.loads(request.body)['type']
    print(order_update)
    # order object update
    if type_of_update == 'update':
        print(order_update['order_number'])
        order = Order.objects.get(order_number=order_update['order_number'])
        order.order_type = OrderType.objects.get(id=order_update['order_type'])
        order.shipping_status = ShippingStatus.objects.get(
            id=order_update['shipping_status'])
        order.billing_first_name = order_update['billing_first_name']
        order.billing_last_name = order_update['billing_last_name']
        order.billing_address = order_update['billing_address']
        order.billing_address2 = order_update['billing_address2']
        order.billing_city = order_update['billing_city']
        order.billing_state_code = order_update['billing_state_code']
        order.billing_zip_code = order_update['billing_zip_code']
        order.billing_email = order_update['billing_email']
        order.sub_total = order_update['sub_total']
        order.is_pickup = order_update['is_pickup']
        order.payment_status = PaymentStatus.objects.get(
            id=order_update['payment_status'])
        order.shipping_first_name = order_update['shipping_first_name']
        order.shipping_last_name = order_update['shipping_last_name']
        order.shipping_address = order_update['shipping_address']
        order.shipping_address2 = order_update['shipping_address2']
        order.shipping_city = order_update['shipping_city']

mirmir_proj/mirmir_app/templates/mirmir_app/about.html
{%extends 'mirmir_app/base.html'%}
{%block title%}Mirmir: About{%endblock%}
{%block style%}
<style>
    #container_about_us {
        background-color: rgba(202, 197, 132, 0.7);
        padding-bottom: 5px;
        border-radius: 7px;
    }
</style>
{%endblock%}
{%block body%}
<div class="container" id="container_about_us">
    <h1>This is the 'about us' page.</h1>
    <p>This page was not implemented due to time constraints, it would be managed in the same manner as the main page
        elements and shop page elements.</p>
</div>


{%endblock%}

mirmir_proj/mirmir_app/templates/mirmir_app/archive.html
{%extends 'mirmir_app/base.html'%}
{%block title%}Mirmir: Archive{%endblock%}
{%block style%}
{%endblock%}
{%block body%}
<h1>This is the archive page.</h1>


{%endblock%}

mirmir_proj/mirmir_app/templates/mirmir_app/email_password_reset.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>

<body>
    <h2>Username: {{username}}</h2>
    <h2>Click the link below to change your password:</h2>
    <p><a href="{{domain}}{% url 'mirmir_app:change_password' %}?code={{code}}">Change Password</a></p>
</body>

</html>

mirmir_proj/mirmir_app/templates/mirmir_app/email_sent.html
{%extends 'mirmir_app/base.html'%}
{%block title%}Mirmir: Email Sent{%endblock%}
{%block style%}
{%endblock%}
{%block body%}
<h3>Email sent, click link in email body to confirm account.</h3>


{%endblock%}

mirmir_proj/mirmir_app/templates/mirmir_app/employee_base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>

    <!-- font awesome -->
    <script src="https://kit.fontawesome.com/fce573833e.js" crossorigin="anonymous"></script>

    <!-- Vue.js -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <!-- Axios -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.20.0/axios.min.js"
        integrity="sha512-quHCp3WbBNkwLfYUMd+KwBAgpVukJu5MncuQaWXgCrfgcxCJAq/fo+oqrRKOj+UKEmyMCG3tb8RB63W+EmrOBg=="
        crossorigin="anonymous"></script>
    <link rel="icon" href="{% static 'mirmir_app/small_logo.png' %}">

    <title>{%block title%}{%endblock%}</title>
    <style>
        @font-face {
            font-family: 'Metamorphous-Regular';
            src: url('Metamorphous-Regular.otf') format('truetype');
        }

        body {
            font-family: 'Metamorphous-Regular';
        }

        .social_media {
            width: 30px;
        }

        #nav_bottom {
            display: flex;
            justify-content: center;
        }

        #nav_bottom>span {
            margin: 5px;
        }

        #nav_container {
            flex-direction: column;
        }

        #sub_links {
            display: flex;
            justify-content: space-between;
        }

        #customer {
            position: absolute;
            right: 1%;
            top: 1%;
            display: flex;
            flex-direction: row;
        }

        .c-nav {
            color: black;
        }

        .sidenav {
            height: 100%;
            /* 100% Full-height */
            width: 0;
            /* 0 width - change this with JavaScript */
            position: fixed;
            /* Stay in place */
            z-index: 1;
            /* Stay on top */
            top: 0;
            /* Stay at the top */
            left: 0;
            background-color: #111;
            /* Black*/
            overflow-x: hidden;
            /* Disable horizontal scroll */
            padding-top: 60px;
            /* Place content 60px from the top */
            transition: 0.5s;
            /* 0.5 second transition effect to slide in the sidenav */
        }

        /* The navigation menu links */
        .sidenav a {
            padding: 8px 8px 8px 32px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
            transition: 0.3s;
        }

        /* When you mouse over the navigation links, change their color */
        .sidenav a:hover {
            color: #f1f1f1;
        }

        /* Position and style the close button (top right corner) */
        .sidenav .closebtn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 36px;
            margin-left: 50px;
        }

        /* Style page content - use this if you want to push the page content to the right when you open the side navigation */
        #main {
            transition: margin-left .5s;
            padding: 20px;
        }

        /* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
        @media screen and (max-height: 450px) {
            .sidenav {
                padding-top: 15px;
            }

            .sidenav a {
                font-size: 18px;
            }
        }

        #mobile_hamburger {
            position: absolute;
            left: 5%;
            top: 8%;
            border: 3px solid gray;
            border-radius: 5px;
            width: 40px;
            display: flex;
            justify-content: center;
            text-align: center;
            display: none;
        }

        #mobile_hamburger i {
            font-size: xx-large;
            text-align: center;
        }

        @media only screen and (max-width: 768px) {
            #hamburger {
                display: none;
            }

            #mobile_hamburger {
                display: flex;
            }
        }
    </style>
    {% block style %}
    {%endblock%}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div id="nav_container" class="container">
            <div class="row">
                <a class="navbar-brand" href="{% url 'mirmir_app:employee_main' %}">Mirmir's Well Meadery</a>
            </div>
            <div class="row" id="logo">
                <img src="http://placekitten.com/80/80" alt="">
            </div>
            <div class="row">

                <!-- desktop nav -->
                <button class="navbar-toggler" id="hamburger" type="button" data-toggle="collapse"
                    data-target="#hamburger" aria-controls="hamburger" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="desk_nav">
                    <div class="navbar-nav mr-auto" id="sub_links">
                        <a class="nav-link" href="{% url 'mirmir_app:main_page_management' %}">Main Page Management</a>
                        <a class="nav-link" href="#">About Us Page Management</a>
                        <a class="nav-link" href="#">Search</a>
                        <a class="nav-link" href="#">Archive</a>
                    </div>
                </div>
            </div>
            <div class="collapse navbar-collapse" id="acct_cart">
                <span class="nav-item" id="customer">
                    <a class="btn nav-link" href="{% url 'mirmir_app:logout' %}" tabindex="-1" aria-disabled="true">Log
                        Out</a>
                </span>
            </div>


            <!-- mobile nav -->
            <span id="mobile_hamburger" onclick="openNav()"><i class="fas fa-bars"></i></span>
            <div class="sidenav" id="mobile_nav">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                <a class="nav-link" href="{% url 'mirmir_app:employee_main' %}">Orders and Product Management</a>
                <a class="nav-link" href="{% url 'mirmir_app:main_page_management' %}">Main Page Management</a>
                <a class="nav-link" href="#">About Us Page Management</a>
                <a class="nav-link" href="#">Search</a>
                <a class="nav-link" href="#">Archive</a>
                <a class="nav-link" href="{% url 'mirmir_app:logout' %}" tabindex="-1" aria-disabled="true">Log
                    Out</a>
            </div>
        </div>
    </nav>
    {%block body%}
    {%endblock%}


    <script>
        /* Set the width of the side navigation to 250px */
        function openNav() {
            document.getElementById("mobile_nav").style.width = "250px";
        }

        /* Set the width of the side navigation to 0 */
        function closeNav() {
            document.getElementById("mobile_nav").style.width = "0";
        }

        // tooltip jQuery
        $('#desktop_username').ready(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
    {%block javascript%}
    {%endblock%}
</body>

</html>

mirmir_proj/mirmir_app/templates/mirmir_app/employee_email.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>

<body>
    <h1>From Us At Mirmir's Well Meadery</h1>
    <div>{{email_text}}</div>
</body>

</html>

mirmir_proj/mirmir_app/templates/mirmir_app/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="icon" href="{% static 'mirmir_app/small_logo.png' %}">

    <title>Mirmir's Well Meadery</title>
    <style>
        body {
            background-image: url("{% static 'mirmir_app/background.jpg' %}");
        }

        #body_main {
            margin-top: 4rem;

        }

        #body_main>.row {
            justify-content: center;
        }

        .row>a {
            margin: 5px;
        }

        img {
            max-height: 700px;
        }

        .row>span {
            background-color: rgba(255, 255, 240, 0.5);
            border-radius: 7px;
            margin-bottom: 15px;
        }

        @media only screen and (max-width: 1000px) {
            img {
                max-height: 300px;
            }
        }
    </style>
</head>

<body>
    <div class="container" id="body_main">
        <div class="row"><span>Do not continue unless you are 21 years of age or older.</span></div>
        <div class="row"><img src="{% static 'mirmir_app/large_logo.png' %}" alt=""></div>
        <div class="row">
            <a href="{%url 'mirmir_app:main'%}" class="btn btn-success">Yes, I am 21 or older.</a>
            <a onclick="goBack()" class="btn btn-danger">No, how did I get here! Let me out!</a>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <script>
        function goBack() {
            window.history.back()
        }
    </script>
</body>

</html>

mirmir_proj/mirmir_app/templates/mirmir_app/login.html
{%extends 'mirmir_app/base.html'%}
{%block title%}Mirmir: Log-In{%endblock%}
{%block style%}
<style>
    #div_body {
        background-color: rgba(255, 255, 240, 0.7);
        padding-bottom: 5px;
        border-radius: 7px;
    }
</style>
{%endblock%}
{%block body%}
<div class="container" id="div_body">
    <h3>User Login</h3>
    {% if there_is_a_message %}
    <div class="alert alert-danger" role="alert">
        {{message}}
    </div>
    {% endif %}
    <form id="form_input" action="{% url 'mirmir_app:login' %}" method="POST">
        {% csrf_token %}
        <input type="text" placeholder="username" name="username" required>
        <input type="password" placeholder="password" name="password" required>
        <input type="hidden" id="recaptcha" name="g-recaptcha-response">
        <!-- <button class="btn btn-primary g-recaptcha" data-sitekey="6LdLbdQZAAAAAFPUDUmXHIDFo7tjwHyUDb40W-lG"
            data-callback="onSubmit" data-action="submit" type="submit">Login</button> -->
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
    <a href="{% url 'mirmir_app:register' %}">
        <h5>Not Registered? Click here to create an account!</h5>
    </a>
    <a href="{% url 'mirmir_app:reset_password_request' %}">
        <h5>Need a password reset? Click here to request an email to reset your password.</h5>
    </a>
</div>


{%endblock%}
{% block javascript %}
<script src="https://www.google.com/recaptcha/api.js?render={{site_key}}"></script>
<script>
    // function onSubmit(token) {
    //     document.getElementById("form").submit();
    // }
    grecaptcha.ready(function () {
        // 4
        $('#form_input').submit(function (e) {
            let form = this;
            // 5
            e.preventDefault()
            grecaptcha.execute('{{ site_key }}', { action: 'form' }).then(function (token) {
                console.log(token)
                // 6
                $('#recaptcha').val(token)
                // 7
                form.submit()
            });
        })
    });
</script>
{% endblock %}

mirmir_proj/mirmir_app/templates/mirmir_app/two_fa.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>

<body>
    <h1>Confirm Your Account</h1>
    <p>Click the link below to confirm your account login:</p>
    <p><a href="{{domain}}{% url 'mirmir_app:confirm_login' %}?code={{code}}">confirm</a></p>
</body>

</html>